<?php 
/**
* Ifthenpay_Payment module dependency
*
* @category    Gateway Payment
* @package     Ifthenpay_Payment
* @author      Ifthenpay
* @copyright   Ifthenpay (http://www.ifthenpay.com)
* @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<img id="mbwayLogoUrl" src="<?php echo $this->getViewFileUrl('Ifthenpay_Payment::images/mbway.svg'); ?>" style="display:none;">

